# Generated by Django 4.1.2 on 2023-02-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="new project",
                        max_length=30,
                        null=True,
                        verbose_name="压测名称",
                    ),
                ),
                (
                    "scripts",
                    models.CharField(
                        default="", max_length=500, null=True, verbose_name="压测脚本名称"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        null=True,
                        verbose_name="压测计划",
                    ),
                ),
            ],
        ),
    ]
