# Generated by Django 4.1.2 on 2023-02-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="Projects",
        ),
    ]
