# Generated by Django 4.1.2 on 2023-02-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_rename_project_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="scripts",
            field=models.CharField(
                default="[]", max_length=500, null=True, verbose_name="压测脚本名称"
            ),
        ),
    ]
