# Generated by Django 4.1.2 on 2023-02-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_projects_scripts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="任务创建时间"),
                ),
                (
                    "des",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("tasks_id", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="队列中", max_length=10, null=True
                    ),
                ),
            ],
        ),
    ]
