# Generated by Django 4.1.2 on 2023-02-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_rename_tasks_id_tasks_project_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DB_django_task_mq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("message", models.TextField(default="{}")),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
