# Generated by Django 4.1.2 on 2023-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_db_django_task_mq"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="mq_id",
            field=models.IntegerField(default=0, verbose_name="mq的id"),
        ),
        migrations.AddField(
            model_name="tasks",
            name="stop",
            field=models.BooleanField(default=False, verbose_name="异常终止"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="des",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True, verbose_name="任务描述"
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="project_id",
            field=models.IntegerField(default=0, verbose_name="项目id"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.CharField(
                blank=True, default="队列中", max_length=10, null=True, verbose_name="正常状态"
            ),
        ),
    ]
